FpRegs.hpp: Add mising include
Add the missing String include. This fixes compiler errors like below
seen on GCC 10.1

FpRegs.hpp:236:10: error: ‘string’ in namespace ‘std’ does not name a type
  236 |     std::string regName(unsigned i, bool abiNames = false) const

Signed-off-by: Alistair Francis <alistair.francis@wdc.com>